server:
  port: 8081
spring:
#  application:
#    name: JOBS-SERVICE
  jpa: 
    hibernate:
      ddl-auto: none
      show-sql: true
      generate-ddl: true
  datasource: 
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: root
logging: 
  level:
    org.hibernate:
      SQL: DEBUG
      type: TRACE
    
