server:
  port: 8030
spring:
  application:
    name: HYSTRIX-SERVICE
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org: 
     springframework: 
       web: DEBUG
management: 
  endpoints: 
    web:
      exposure:
        include: hystrix.stream
        