server:
  port: 9000
spring:
  application:
    name: zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka 
zuul:
  prefix: /bookapi
  routes:
   BOOK-SERVICE: 
    path: /books/**
    service-id: BOOK-SERVICE
   ORDER-SERVICE:  
    path: /orders/**
    service-id: ORDER-SERVICE
#    url: http://ORDER-SERVICE/