server:
  port: 8085
#  error:
#    whitelabel:
#      enabled: false
spring:
  application:
    name: FEIGN-CLIENT
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign: 
  hystrix: 
    enabled: true
            